export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const SET_SESSION = 'SET_SESSION';
export const ACTION_TEST = 'ACTION_TEST';

export const FETCH_STATS_PENDING = 'FETCH_STATS_PENDING';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_ERROR = 'FETCH_STATS_ERROR';
export const SET_INFECTION_TREE = 'SET_INFECTION_TREE';
export const SET_SIMULATION_TREE = 'SET_SIMULATION_TREE';
export const EXIT_SIMULATION = 'EXIT_SIMULATION';
export const SET_OFFICE_STATISTICS = 'SET_OFFICE_STATISTICS';
export const SET_WRISTBAND_DATA = 'SET_WRISTBAND_DATA';
export const SET_USER_LIST = 'SET_USER_LIST';
export const SET_PEOPLE_STATISTICS = 'SET_PEOPLE_STATISTICS';
export const SET_ROOM_STATISTICS = 'SET_ROOM_STATISTICS';
